services:
  slamdunk:
    build: .
    image: "registry.sidtrz.com:5000/slamdunk:dev"
    privileged: true
    network_mode: host
    ports:
      - "5801:5801"
      - "5802:5802"
      - "5805:5805"
      - "5806:5806"
    volumes:
      - ./data:/home/jetson/app/data
    device_cgroup_rules:
      - 'c 81:* rm'
    environment:
      SLAMDUNK_HOST: $HOSTNAME
    restart: always
    container_name: slamdunk
  visualisation:
    image: "registry.sidtrz.com:5000/lichtblick:latest"
    ports:
      - "5803:8080"
    volumes:
      - ./extern/foxglove/Default.json:/lichtblick/default-layout.json
    restart: always
